import { useState } from 'react';
import { Calculator, Check, ChevronDown, ClipboardCheck, Copy, MessageCircle, RefreshCw, ShieldCheck, Sparkles } from 'lucide-react';
import { PricingCalculator } from '../components/PricingCalculator';

type Section = 'scripts' | 'diagnostic' | 'objections' | 'cadence' | 'pricing';
const scripts = [
  { id: 'indicacao', title: 'Abordagem por indicação', moment: 'Primeiro contato', channel: 'WhatsApp', content: `Oi, [nome]. Tudo bem? O [indicador] comentou sobre a [empresa] e me chamou atenção [observação real sobre o negócio].\n\nEu ajudo empresas a organizar [área/problema percebido] para gerar mais oportunidades e não perder vendas por falta de estrutura.\n\nAntes de falar em qualquer solução, queria entender como vocês fazem isso hoje. Faz sentido uma conversa rápida de 20 minutos nesta semana?` },
  { id: 'prospeccao', title: 'Prospecção direta', moment: 'Primeiro contato', channel: 'WhatsApp / LinkedIn', content: `Olá, [nome]. Tudo bem? Sou Fernando Ramalho, fundador da Orientohub.\n\nAo longo da minha trajetória, já atendi mais de 100 empresas e percebi um desafio comum: encontrar um parceiro estratégico que realmente entenda o negócio como um todo.\n\nFoi por isso que criei a Orientohub, conectando estratégia e execução conforme a realidade de cada empresa. Quando surgir um desafio no seu negócio, pode contar comigo.` },
  { id: 'reuniao', title: 'Abertura da reunião', moment: 'Diagnóstico', channel: 'Call / presencial', content: `Obrigado pelo tempo, [nome]. Minha ideia hoje não é apresentar a Orientohub nem tentar te vender um pacote. Quero entender como o negócio funciona, onde vocês querem chegar e o que está travando esse avanço.\n\nSe eu enxergar uma forma concreta de ajudar, no final eu explico o caminho que recomendo. Se não fizer sentido, também vou dizer. Combinado?` },
  { id: 'oferta', title: 'Transição para a oferta', moment: 'Fechamento', channel: 'Call / presencial', content: `Pelo que você me contou, o problema central não é [sintoma]. É [causa diagnosticada], e isso hoje está custando [impacto citado pelo cliente].\n\nMinha recomendação é começar por [serviço], porque ele resolve primeiro [prioridade] e cria a base para [resultado desejado].\n\nO escopo inclui [entregáveis], acontece em [prazo] e o investimento é [valor]. Faz sentido avançarmos assim?` },
  { id: 'followup', title: 'Follow-up da proposta', moment: 'Após proposta', channel: 'WhatsApp', content: `Oi, [nome]. Retomando nossa conversa: você comentou que [dor nas palavras do cliente] e que precisa [resultado desejado].\n\nA proposta foi desenhada para sair de [estado atual] e chegar a [estado futuro], começando por [primeiro passo].\n\nFicou alguma dúvida sobre o caminho ou existe algo impedindo a decisão agora?` },
  { id: 'reativacao', title: 'Reativação sem pressão', moment: 'Lead parado', channel: 'WhatsApp', content: `Oi, [nome]. Lembrei da nossa conversa sobre [problema]. Isso ainda é uma prioridade para a [empresa] ou o cenário mudou?\n\nEstou reorganizando os projetos deste mês e, se ainda fizer sentido, posso atualizar a recomendação com um primeiro passo mais enxuto.` },
];
const diagnostic = [['Contexto', 'Como a empresa gera clientes hoje? O que já funciona bem?'], ['Meta', 'Qual resultado vocês precisam alcançar nos próximos 90 dias?'], ['Problema', 'O que mais impede esse resultado hoje? Há quanto tempo?'], ['Impacto', 'O que esse problema custa em vendas, tempo ou oportunidades?'], ['Tentativas', 'O que vocês já tentaram e por que não resolveu?'], ['Decisão', 'Além de você, quem participa da decisão?'], ['Urgência', 'O que acontece se nada mudar nos próximos seis meses?'], ['Investimento', 'Existe uma faixa reservada para resolver essa prioridade?']];
const objections = [
  ['“Está caro.”', 'Caro em relação ao orçamento disponível ou ao retorno que ficou pouco claro? Vamos separar as duas coisas. Se o escopo estiver grande, podemos começar pela etapa de maior retorno sem desmontar a solução.'],
  ['“Preciso pensar.”', 'Claro. O que exatamente você precisa avaliar: prioridade, confiança na solução, investimento ou alinhamento com outra pessoa? Posso ajudar a responder isso agora.'],
  ['“Vou falar com meu sócio.”', 'Perfeito. O que ele precisa enxergar para se sentir seguro? Se preferir, fazemos uma conversa curta juntos para que a análise não chegue pela metade.'],
  ['“Agora não é o momento.”', 'O que precisaria acontecer para virar o momento certo? Podemos definir uma data objetiva ou um primeiro passo menor.'],
  ['“Já tenho alguém que faz isso.”', 'Ótimo — não quero substituir algo que funciona. Onde ainda existe uma lacuna? Podemos atuar em uma frente complementar e bem definida.'],
];
const cadence = [['D0', 'Enviar proposta no mesmo dia', 'Recapitule dor, impacto, resultado, escopo, prazo e próximo passo.'], ['D2', 'Confirmar entendimento', 'Pergunte se algo ficou pouco claro.'], ['D5', 'Retomar a consequência', 'Use a dor nas palavras do cliente e responda uma possível objeção.'], ['D9', 'Adicionar valor', 'Envie uma observação ou ação útil ligada ao diagnóstico.'], ['D14', 'Fechar o ciclo', 'Peça uma decisão honesta: avançar, reagendar ou encerrar.'], ['D30', 'Reativar', 'Volte com contexto novo e verifique se a prioridade mudou.']];

export const PlaybookPage = () => {
  const [section, setSection] = useState<Section>('scripts');
  const [copied, setCopied] = useState('');
  const [openObjection, setOpenObjection] = useState(0);
  const copy = async (id: string, text: string) => { await navigator.clipboard.writeText(text); setCopied(id); window.setTimeout(() => setCopied(''), 1600); };
  const tabs: [Section, string, typeof MessageCircle][] = [['scripts', 'Scripts', MessageCircle], ['diagnostic', 'Diagnóstico', ClipboardCheck], ['objections', 'Objeções', ShieldCheck], ['cadence', 'Cadência', RefreshCw], ['pricing', 'Precificação', Calculator]];
  return <div className="playbook-page">
    <header className="playbook-hero"><div><p className="eyebrow">Máquina comercial</p><h1>Playbook de vendas</h1><p>Direção prática para conduzir cada conversa do primeiro contato ao fechamento.</p></div><aside><Sparkles /><div><span>Regra de ouro</span><strong>Dor → impacto → prioridade → serviço → resultado</strong></div></aside></header>
    <nav className="playbook-tabs">{tabs.map(([id, label, Icon]) => <button key={id} className={section === id ? 'active' : ''} onClick={() => setSection(id)}><Icon size={16} />{label}</button>)}</nav>
    {section === 'scripts' && <div className="script-grid">{scripts.map((script) => <article className="script-card" key={script.id}><header><div><span>{script.moment}</span><small>{script.channel}</small><h2>{script.title}</h2></div><button onClick={() => copy(script.id, script.content)}>{copied === script.id ? <Check size={14} /> : <Copy size={14} />}{copied === script.id ? 'Copiado' : 'Copiar'}</button></header><p>{script.content}</p></article>)}</div>}
    {section === 'diagnostic' && <section className="playbook-panel"><header><p className="eyebrow">Roteiro de descoberta</p><h2>Pergunte, aprofunde e registre as palavras exatas</h2></header><div className="diagnostic-list">{diagnostic.map(([label, question], index) => <article key={label}><b>{index + 1}</b><span>{label}</span><p>{question}</p></article>)}</div></section>}
    {section === 'objections' && <section className="playbook-panel"><header><p className="eyebrow">Objeção não é rejeição</p><h2>Descubra o risco que ainda não foi resolvido</h2></header><div className="objection-list">{objections.map(([title, answer], index) => <article key={title}><button onClick={() => setOpenObjection(openObjection === index ? -1 : index)}><strong>{title}</strong><ChevronDown className={openObjection === index ? 'rotated' : ''} /></button>{openObjection === index && <div><p>{answer}</p><button onClick={() => copy(`ob-${index}`, answer)}>{copied === `ob-${index}` ? <Check size={14} /> : <Copy size={14} />}{copied === `ob-${index}` ? 'Copiado' : 'Copiar resposta'}</button></div>}</article>)}</div></section>}
    {section === 'cadence' && <section className="playbook-panel"><header><p className="eyebrow">Régua de follow-up</p><h2>Persistência com contexto, nunca cobrança vazia</h2></header><div className="cadence-list">{cadence.map(([day, action, detail]) => <article key={day}><b>{day}</b><div><strong>{action}</strong><p>{detail}</p></div></article>)}</div></section>}
    {section === 'pricing' && <PricingCalculator />}
  </div>;
};
