import { motion } from 'framer-motion';
import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';
import { ArrowLeft, ArrowRight, BarChart3, CheckCircle2, LineChart, Megaphone, PenTool, Target } from 'lucide-react';
import type { ServiceCatalogItem } from '../data/serviceCatalog';

const money = (value: number) => value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });

const MarketingServicePage = ({ service }: { service: ServiceCatalogItem }) => (
  <>
    <Helmet><title>Marketing | Serviços OrientoHub</title><meta name="description" content={service.description} /></Helmet>
    <main className="relative isolate overflow-hidden bg-gradient-to-br from-black via-gray-900 to-black text-white">
      <div className="pointer-events-none absolute inset-0 z-0 opacity-20" style={{ backgroundImage: 'radial-gradient(circle at 2px 2px, #FFF200 1px, transparent 0)', backgroundSize: '40px 40px' }} />
      <section className="relative z-10 border-b border-white/10"><div className="container-custom py-14 sm:py-20 lg:py-28"><Link to="/servicos" className="inline-flex items-center gap-2 text-sm font-semibold text-white/50 transition hover:text-[#FFF200]"><ArrowLeft className="h-4 w-4" />Todos os serviços</Link><div className="mt-12 grid gap-12 lg:grid-cols-[1.15fr_0.85fr] lg:items-end">
        <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }}><p className="flex items-center gap-3 text-xs font-black uppercase tracking-[0.24em] text-[#FFF200]"><span className="h-px w-10 bg-[#FFF200]" />Marketing estratégico</p><h1 className="mt-6 text-[clamp(2.75rem,5.4vw,4.75rem)] font-black leading-[0.94] tracking-[-0.05em]"><span className="block">Presença que</span><span className="mt-2 block whitespace-nowrap text-[#FFF200]">gera demanda.</span></h1><p className="mt-7 max-w-2xl text-lg leading-relaxed text-white/60 sm:text-xl">{service.outcome}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#planos-marketing" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#FFF200] px-6 py-4 text-sm font-black uppercase tracking-wide text-black transition hover:bg-white">Conhecer os planos <ArrowRight className="h-4 w-4" /></a><Link to="/contato?service=Marketing" className="inline-flex items-center justify-center border border-white/20 px-6 py-4 text-sm font-bold transition hover:border-[#FFF200] hover:text-[#FFF200]">Falar com especialista</Link></div></motion.div>
        <motion.aside initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} className="rounded-2xl border border-[#FFF200]/35 bg-gray-900/85 p-7 backdrop-blur-md sm:p-9"><div className="flex items-center justify-between"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#FFF200] text-black"><Megaphone className="h-6 w-6" /></span><span className="rounded-full border border-[#FFF200]/35 bg-[#FFF200]/10 px-3 py-1 text-xs font-black uppercase tracking-wider text-[#FFF200]">A partir de R$ 1.497/mês</span></div><p className="mt-8 text-xs font-black uppercase tracking-[0.2em] text-white/35">Uma operação conectada</p><ul className="mt-5 space-y-5">{['Posicionamento que diferencia', 'Conteúdo com direção estratégica', 'Criativos que movimentam o público', 'Indicadores para ajustar a rota'].map((item, index) => <li key={item} className="flex items-start gap-4 border-b border-white/10 pb-5 last:border-0 last:pb-0"><span className="text-xs font-black text-[#FFF200]">0{index + 1}</span><span className="font-semibold text-white/85">{item}</span></li>)}</ul></motion.aside>
      </div></div></section>

      <section className="relative z-10 container-custom py-16 sm:py-24"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:gap-16"><div><p className="text-xs font-black uppercase tracking-[0.22em] text-[#FFF200]">Além de publicar</p><h2 className="mt-4 text-4xl font-black tracking-[-0.04em] sm:text-5xl">Marca, conteúdo e resultado na mesma direção.</h2><p className="mt-5 text-lg leading-relaxed text-white/50">A presença digital deixa de ser uma sequência de tarefas e passa a operar como parte da estratégia do negócio.</p></div><div className="grid gap-4 sm:grid-cols-2">{service.deliverables.map((item, index) => <motion.div key={item} initial={{ opacity: 0, y: 12 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="rounded-2xl border border-[#FFF200]/30 bg-gray-900/70 p-6"><span className="text-xs font-black text-[#FFF200]">0{index + 1}</span><p className="mt-8 text-lg font-bold">{item}</p></motion.div>)}</div></div></section>

      <section id="planos-marketing" className="relative z-10 border-y border-white/10 bg-black/35"><div className="container-custom py-16 sm:py-24"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-black uppercase tracking-[0.22em] text-[#FFF200]">Planos de marketing</p><h2 className="mt-4 text-4xl font-black sm:text-5xl">Estrutura para cada fase do negócio.</h2><p className="mt-4 text-white/50">Escolha o nível de produção e acompanhamento ideal para o seu momento.</p></div><div className="mt-12 grid items-stretch gap-4 md:grid-cols-2 xl:grid-cols-4">{service.plans?.map((plan, index) => <motion.article key={plan.name} initial={{ opacity: 0, y: 12 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.05 }} className={`relative flex flex-col rounded-2xl border p-5 ${plan.featured ? 'border-[#FFF200] bg-[#FFF200] text-black' : 'border-[#FFF200]/30 bg-gray-900/80 text-white'}`}>{plan.featured && <span className="absolute -top-3 left-1/2 -translate-x-1/2 whitespace-nowrap rounded-full bg-black px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-[#FFF200]">Mais contratado</span>}<p className={`text-[10px] font-bold uppercase tracking-wider ${plan.featured ? 'text-black/60' : 'text-[#FFF200]'}`}>Plano</p><h3 className="mt-1 text-2xl font-bold">{plan.name}</h3><p className="mt-2 text-sm font-bold uppercase">{plan.subtitle}</p><p className={`mt-5 min-h-[60px] text-sm ${plan.featured ? 'text-black/70' : 'text-white/50'}`}>{plan.audience}</p><div className={`my-5 border-t ${plan.featured ? 'border-black/20' : 'border-white/10'}`} /><ul className="flex-1 space-y-3">{plan.features.map(feature => <li key={feature} className="flex gap-2 text-sm"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0" />{feature}</li>)}</ul><div className={`mt-6 border-t pt-5 ${plan.featured ? 'border-black/20' : 'border-white/10'}`}><p className="text-[10px] font-bold uppercase">{plan.startingAt ? 'A partir de' : 'Investimento'}</p><p className="mt-1 text-3xl font-bold">{money(plan.price)}<span className="text-sm opacity-60">/mês</span></p><Link to={`/contato?service=Marketing&message=${encodeURIComponent(`Tenho interesse no plano ${plan.name}.`)}`} className={`mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-bold ${plan.featured ? 'bg-black text-white' : 'bg-[#FFF200] text-black'}`}>Quero este plano <ArrowRight className="h-4 w-4" /></Link></div></motion.article>)}</div><p className="mt-5 text-center text-xs text-white/45">* Investimento em mídia e desenvolvimento contratado separadamente.</p></div></section>

      <section className="relative z-10 container-custom py-16 sm:py-24"><p className="text-xs font-black uppercase tracking-[0.22em] text-[#FFF200]">Como trabalhamos</p><h2 className="mt-4 text-4xl font-black sm:text-5xl">Estratégia, consistência e evolução.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{service.process.map((step, index) => { const Icon = [Target, PenTool, LineChart][index] || BarChart3; return <article key={step.title} className="rounded-2xl border border-[#FFF200]/30 bg-gray-900/75 p-7"><Icon className="h-7 w-7 text-[#FFF200]" /><h3 className="mt-8 text-2xl font-black">{step.title}</h3><p className="mt-3 text-white/50">{step.description}</p></article>; })}</div></section>
    </main>
  </>
);

export default MarketingServicePage;
