import { FormEvent, useState } from 'react';
import { CalendarCheck2, X } from 'lucide-react';
import { crm } from '../services/crm';
import { CustomSelect } from './CustomSelect';

export const TaskDrawer = ({ dealId, dealName, onClose, onCreated }: { dealId: string; dealName: string; onClose: () => void; onCreated: () => void }) => {
  const [form, setForm] = useState({ title: '', description: '', startsAt: '', endsAt: '', type: 'task' });
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { await crm.createTask({ deal_id: dealId, title: form.title.trim(), description: form.description.trim() || null, starts_at: form.startsAt ? new Date(form.startsAt).toISOString() : null, ends_at: form.endsAt ? new Date(form.endsAt).toISOString() : null, task_type: form.type }); onCreated(); onClose(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível criar a tarefa.'); } finally { setSaving(false); } };
  return <div className="drawer-backdrop" onMouseDown={onClose}><aside className="drawer" onMouseDown={(event) => event.stopPropagation()}><header><div><span><CalendarCheck2 size={19} /></span><div><p>{dealName}</p><h2>Criar tarefa</h2></div></div><button onClick={onClose} aria-label="Fechar"><X /></button></header><form onSubmit={submit}><div className="drawer-body"><label className="drawer-field">Assunto <b>*</b><input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="O que precisa ser feito?" /></label><label className="drawer-field">Descrição<textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Contexto e resultado esperado" /></label><label className="drawer-field">Tipo<CustomSelect value={form.type} onChange={(type) => setForm({ ...form, type })} options={[{ value: 'task', label: 'Tarefa' }, { value: 'call', label: 'Ligação' }, { value: 'meeting', label: 'Reunião' }, { value: 'follow_up', label: 'Follow-up' }]} /></label><div className="form-grid"><label className="drawer-field">Início<input type="datetime-local" value={form.startsAt} onChange={(event) => setForm({ ...form, startsAt: event.target.value })} /></label><label className="drawer-field">Fim<input type="datetime-local" min={form.startsAt} value={form.endsAt} onChange={(event) => setForm({ ...form, endsAt: event.target.value })} /></label></div>{error && <p className="drawer-error">{error}</p>}</div><footer><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving}>{saving ? 'Salvando…' : 'Criar tarefa'}</button></footer></form></aside></div>;
};
